server:
  port: 9090
spring:
  application:
    name: UMA
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost/usermanagementapp
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  
  #smtp properties 
  mail:
    default-encoding: UTF-8
    host : gmail.smtp.com
    port : 587
    username : gpganeshpatekar@gmail.com
    password : 
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true
    protocol: smtp
    test-connection: false
    
  app:
    messages:
      #userServiceImpl messages
      acountLocked : Your Account is Locked
      loginSuccess : Login successful.. Welcome To Bikkad IT
      invalidCreditionals : Creditionals Are Invalid

      checkMailToUnlock : Please check Your Mail To Unlock Account
      restPassMail : Password is sent to you email id, Check your mail

      #UserController
      saveSuccess : User Saved Successfully.. Check Your Email For Unlock Account..
      saveUnsuccess : User Not Saved Successfully
      #UnlcokAccountController
      unlockAccount : Account Unlock
      failedToUnlock : Failed To Unlcok Account